### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/tame-oidc#20]
@MarcusGrass did a large PR with #15 and we've been using that temporarily as a git fork for a few weeks now, but we should do a proper release of the crate and switch away from the fork in `ark`. 

Can you do that @MarcusGrass , with some help from @Jake-Shadle maybe?

**Comment by vojd** [comment]
New release out, 0.5.0
https://github.com/EmbarkStudios/tame-oidc/tree/0.5.0
